# Generated by Django 4.2.3 on 2024-03-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user_id',
            new_name='user',
        ),
    ]
