# Generated by Django 4.2.3 on 2024-02-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='default_image.jpg', upload_to='blog-post-image'),
        ),
    ]
